import type { Locale, PresetEventCategory, PresetEventDefinition } from '../types'

const GOUACHE = 'editorial matte gouache, mineral teal, indigo, sage and warm copper, visible dry-brush edges, grounded contemporary coastal fantasy, no photorealism, no glossy 3D, no readable text, no letters, no logos, no UI, 4:3'
const POV = 'FIRST-PERSON PLAYER-EYE VIEW, protagonist entirely out of frame, no protagonist face, head, back, shoulders, reflection, silhouette, body or invented hands'

type Pair = [zh: string, en: string]
interface LocalizedPresetEvent {
  id: string
  locationId: string
  category: PresetEventCategory
  choiceLabel: Pair
  text: Pair
  objective: Pair
  choices: [Pair, ...Pair[]]
  imagePrompt: string
}

const events: LocalizedPresetEvent[] = [
  {
    id: 'lantern-quay-sealed-box', locationId: 'lantern-quay', category: 'environment',
    choiceLabel: ['查看石阶边漂来的封蜡木盒', 'Inspect the wax-sealed wooden box by the quay steps'],
    text: ['退潮把一只巴掌大的木盒留在石阶边。封蜡没有字，盒角却嵌着三粒银白盐砂；码头保管员拿来夹钳，没有替你打开。', 'The ebb tide leaves a palm-sized wooden box beside the stone steps. Its wax bears no writing, but three grains of silver-white salt sit in one corner; the quay keeper brings tongs without opening it for you.'],
    objective: ['决定如何检查石阶边的封蜡木盒。', 'Decide how to examine the wax-sealed box by the quay steps.'],
    choices: [['请保管员先核对失物记录', 'Ask the keeper to check the lost-property record first'], ['隔着夹钳检查盒底和封蜡', 'Inspect the base and wax with the tongs'], ['不碰木盒，沿退潮水线找来源', 'Leave the box untouched and trace the ebb line']],
    imagePrompt: `${POV}, a quay keeper extending long brass tongs toward one small wax-sealed wooden box on wet stone steps, three pale salt grains visible, evening water beyond, ${GOUACHE}`,
  },
  {
    id: 'lantern-quay-missing-kettle', locationId: 'lantern-quay', category: 'daily-life',
    choiceLabel: ['帮渡口厨房找回错送的铜水壶', 'Help the ferry kitchen recover its misdelivered copper kettle'],
    text: ['渡口厨房准备晚汤时少了一只矮铜壶。厨工在货签绳里找到同色的蓝麻结，说明水壶被送去了附近某个雨棚，却还不知道是哪一个。', 'As the ferry kitchen prepares evening soup, one squat copper kettle is missing. A cook finds a blue flax knot among the cargo cords, showing it went to a nearby awning, though nobody knows which one.'],
    objective: ['沿蓝麻结找回渡口厨房的铜水壶。', 'Follow the blue flax knot to recover the ferry kitchen kettle.'],
    choices: [['检查鱼贩雨棚的蓝麻结', 'Check the blue flax knot at the fishmonger’s awning'], ['询问搬运工最后搬过哪批厨具', 'Ask the porters which kitchenware they moved last'], ['留在厨房核对还缺哪些器具', 'Stay in the kitchen and check what else is missing']],
    imagePrompt: `${POV}, an adult ferry cook holding one blue flax cargo knot beside an empty circular place on a kitchen shelf, steaming soup pots behind, ${GOUACHE}`,
  },
  {
    id: 'lantern-quay-awning-seam', locationId: 'lantern-quay', category: 'local-work',
    choiceLabel: ['查看即将漏雨的月台雨棚接缝', 'Inspect the platform awning seam before it leaks'],
    text: ['一阵海风把月台雨棚掀起半尺，最外侧接缝已经松开。维修领班把绳、梯子和报酬簿放在干燥处，说明要先看过接缝，才会报出工时和钱数。', 'A sea gust lifts the platform awning half a foot, loosening its outer seam. The repair lead sets rope, a ladder, and the pay ledger in a dry place, explaining that the seam must be inspected before hours and wages can be quoted.'],
    objective: ['先判断月台雨棚接缝需要怎样修。', 'Determine what the platform awning seam needs before taking the job.'],
    choices: [['站在地面检查松开的绳扣', 'Inspect the loose rope fasteners from the ground'], ['问领班检查后如何计算报酬', 'Ask how the lead will calculate pay after inspection'], ['提醒候车人离开最外侧雨棚', 'Move waiting passengers away from the outer awning']],
    imagePrompt: `wide upward view of one lifted canvas awning seam and loose rope fasteners above a rain-wet coastal platform, workers small at the edge, protagonist absent, ${GOUACHE}`,
  },
  {
    id: 'lantern-quay-route-courier', locationId: 'lantern-quay', category: 'cross-region',
    choiceLabel: ['听沿线信使说明一段中断的邮路', 'Hear a route courier explain a broken mail connection'],
    text: ['一名沿线信使把三只未拆的防水邮袋排在长凳上。通往风崖、渡村和浴镇的绳结都完好，只有果园方向的扣环被新泥堵住，信使请你只凭外部痕迹判断绕路。', 'A route courier sets three unopened waterproof mailbags on a bench. The knots for the cliffs, crossing, and baths are sound; only the orchard clasp is clogged with fresh mud, and the courier asks you to judge a detour from outside evidence alone.'],
    objective: ['判断果园邮袋是改道还是留在灯湾。', 'Decide whether the orchard mailbag should detour or remain at Lantern Quay.'],
    choices: [['比较扣环泥土和月台车轮印', 'Compare the mud on the clasp with the platform wheel tracks'], ['问信使果园方向最后一次通车时间', 'Ask when the orchard route last ran'], ['把邮袋留在长凳，先查月线公告', 'Leave the bag on the bench and check Moonline service']],
    imagePrompt: `${POV}, an adult route courier presenting three closed waterproof mailbags on a wooden bench, one clasp visibly clogged with fresh ochre mud, train platform beyond, ${GOUACHE}`,
  },

  {
    id: 'carriage-frost-map', locationId: 'moonline-carriage', category: 'environment',
    choiceLabel: ['辨认车窗霜纹里重复出现的海岸线', 'Trace the coastline repeating in the carriage frost'],
    text: ['车窗内侧结出一道细霜，列车每过一个弯，霜纹里都会露出相同的岬角缺口。窗外真实海岸一闪而过，两者有一段对不上。', 'A fine frost forms inside the carriage window. At every bend, the same notched headland clears through it, while the real coast flashes outside with one section that does not match.'],
    objective: ['比较车窗霜纹与窗外海岸的差异。', 'Compare the frost pattern with the real coastline outside.'],
    choices: [['用窗框边缘对齐岬角缺口', 'Align the notched headland with the window frame'], ['请乘务员指出列车刚经过的弯道', 'Ask the steward which bend the train just passed'], ['记住差异，等到下一扇车窗再核对', 'Remember the mismatch and check the next window']],
    imagePrompt: `${POV}, frost pattern on a dark train window aligning imperfectly with a moonlit notched headland outside, brass window frame in foreground, protagonist absent, ${GOUACHE}`,
  },
  {
    id: 'carriage-sleeping-token', locationId: 'moonline-carriage', category: 'visitor',
    choiceLabel: ['处理熟睡乘客滑到过道的空白票夹', 'Deal with a sleeping passenger’s blank ticket clip in the aisle'],
    text: ['邻座乘客睡着后，一只没有字的银色票夹滑到过道。票夹背面的海盐还湿，说明它刚在某个月台用过；检票员停在两步外，等你决定是否叫醒失主。', 'When a nearby passenger falls asleep, an unmarked silver ticket clip slides into the aisle. Sea salt on its back is still damp, suggesting recent use at a platform; the inspector stops two paces away and waits for your decision.'],
    objective: ['把空白票夹安全交还或交给检票员。', 'Return the blank clip safely or give it to the inspector.'],
    choices: [['轻声叫醒乘客并指出票夹', 'Wake the passenger gently and point out the clip'], ['请检票员暂时保管票夹', 'Ask the inspector to hold the clip'], ['不碰票夹，先确认它是否挡住过道', 'Leave it untouched and check whether it blocks the aisle']],
    imagePrompt: `${POV}, one blank silver ticket clip on a dark train aisle, an adult inspector waiting nearby and a sleeping passenger out of focus, no protagonist body, ${GOUACHE}`,
  },
  {
    id: 'carriage-seat-parcel', locationId: 'moonline-carriage', category: 'cross-region',
    choiceLabel: ['查看座椅下滚出的藤编小包', 'Inspect the woven parcel rolling from beneath a seat'],
    text: ['转弯时，一只扎着白藤带的小包从空座下滚出。包裹没有地址，藤带却沾着葡萄粉和浴镇常见的皂香；车厢里没人认领。', 'On a bend, a small parcel tied with white vine strips rolls from beneath an empty seat. It has no address, but the binding carries grape bloom and the soap scent common at the baths; nobody in the carriage claims it.'],
    objective: ['在不拆包的情况下判断藤编小包的去向。', 'Determine the woven parcel’s route without opening it.'],
    choices: [['让乘务员核对这节车厢的上车站', 'Ask the steward to check boarding stops for this carriage'], ['比较藤带上的葡萄粉和皂香', 'Compare the grape bloom and soap scent on the binding'], ['把小包留在原处等待失主回来', 'Leave the parcel in place and wait for its owner']],
    imagePrompt: `${POV}, one small woven parcel tied with pale vine strips beneath a Moonline seat, faint grape bloom on the binding, warm carriage lamps, ${GOUACHE}`,
  },
  {
    id: 'carriage-dim-lamps', locationId: 'moonline-carriage', category: 'daily-life',
    choiceLabel: ['帮乘务员找出忽明忽暗的车厢灯', 'Help the steward locate the flickering carriage lamp'],
    text: ['车厢灯每隔七次轨缝声就暗一下。乘务员关掉备用灯，发现只有靠近行李架的两盏同时闪烁，怀疑是一处松动接头而不是整节车断电。', 'The carriage lamps dim after every seventh rail joint. The steward switches off the spare light and finds that only the two lamps by the luggage rack flicker together, suggesting one loose connector rather than a carriage-wide outage.'],
    objective: ['找出两盏车厢灯共同的松动接头。', 'Find the shared loose connector for the two carriage lamps.'],
    choices: [['数七次轨缝声后观察哪盏先暗', 'Count seven rail joints and watch which lamp dims first'], ['请乘务员清空灯下行李架', 'Ask the steward to clear the rack beneath the lamps'], ['坐在原位记录闪烁间隔', 'Stay seated and record the flicker interval']],
    imagePrompt: `${POV}, two brass carriage lamps near a luggage rack flickering out of phase, adult steward raising one safe inspection mirror, protagonist absent, ${GOUACHE}`,
  },

  {
    id: 'cupshadow-silent-stage', locationId: 'cupshadow-market', category: 'environment',
    choiceLabel: ['检查突然熄灭的布台脚灯', 'Inspect the cloth stage footlights that suddenly went dark'],
    text: ['杯影夜市的小布台刚换完场，四盏脚灯却从左到右依次熄灭。灯芯没有湿，最右侧铜碟里多了一层细白粉末。', 'The small cloth stage at Cupshadow has just changed acts when four footlights go dark from left to right. The wicks are dry, but a fine white powder coats the rightmost copper dish.'],
    objective: ['判断布台脚灯为何依次熄灭。', 'Determine why the cloth-stage footlights went dark in sequence.'],
    choices: [['检查最右侧铜碟里的白色粉末', 'Inspect the white powder in the rightmost copper dish'], ['问换场工最后碰过哪一盏灯', 'Ask the stagehand which lamp they touched last'], ['沿灯线查看风从哪一侧穿过布台', 'Trace which side the wind crosses the stage']],
    imagePrompt: `${POV}, four low copper stage lamps extinguished in sequence beneath a plum cloth stage, white mineral powder in the nearest dish, no protagonist body, ${GOUACHE}`,
  },
  {
    id: 'cupshadow-borrowed-bowls', locationId: 'cupshadow-market', category: 'daily-life',
    choiceLabel: ['帮夜市摊主分清借来的三摞碗', 'Help a market cook sort three stacks of borrowed bowls'],
    text: ['收摊前，汤摊多出三摞花色相近的碗。摊主只记得青边来自浴镇、粗陶来自渡村，剩下一摞底部沾着葡萄叶灰。', 'Before closing, a soup stall has three extra stacks of similar bowls. The cook remembers that blue rims came from the baths, rough clay from the crossing, and the remaining stack bears grape-leaf ash underneath.'],
    objective: ['把三摞借碗按来源分清。', 'Sort the three borrowed bowl stacks by origin.'],
    choices: [['先分出带青边的浴镇碗', 'Separate the blue-rimmed bowls from the baths'], ['检查粗陶碗底的水痕', 'Inspect the water marks under the rough clay bowls'], ['问隔壁摊主谁带来了葡萄叶灰', 'Ask the neighboring stall who brought grape-leaf ash']],
    imagePrompt: `${POV}, three stacks of ceramic bowls on a market counter, blue rims, rough clay and grape-leaf ash as distinct clues, adult cook opposite, ${GOUACHE}`,
  },
  {
    id: 'cupshadow-fabric-crate', locationId: 'cupshadow-market', category: 'visitor',
    choiceLabel: ['查看送错布台的矿蓝色布箱', 'Inspect the mineral-blue fabric case delivered to the wrong stage'],
    text: ['一名外地搬运工把矿蓝色布箱放在乐台前，却发现这里没有等货的人。箱扣系着浴镇蒸汽房常用的耐湿绳，箱内没有传出碰撞声。', 'An out-of-town porter sets a mineral-blue fabric case before the music stage, but nobody is waiting for it. Its clasp uses the damp-proof cord common in the bath town, and nothing knocks inside.'],
    objective: ['确认矿蓝布箱应该送到哪个夜市布台。', 'Confirm which market stage should receive the mineral-blue case.'],
    choices: [['检查耐湿绳的打结方向', 'Inspect the direction of the damp-proof knot'], ['问搬运工从哪一个月台接货', 'Ask which platform the porter collected it from'], ['请各布台负责人来认箱扣', 'Ask the stage leads to identify the clasp']],
    imagePrompt: `${POV}, an adult porter presenting one mineral-blue fabric case with damp-proof rope beneath night-market awnings, stages blurred beyond, ${GOUACHE}`,
  },
  {
    id: 'cupshadow-wind-chart', locationId: 'cupshadow-market', category: 'cross-region',
    choiceLabel: ['核对摊主手里没有字的风向布片', 'Check the stallholder’s unmarked wind-direction cloth'],
    text: ['香料摊主展开一块没有字的长布，上面只缝着五种方向不同的铜线。昨晚风崖来客说其中一条指向临时停靠站，摊主却不愿凭传闻给旅人带路。', 'A spice seller unfolds an unmarked long cloth stitched with five differently angled copper threads. A visitor from the cliffs said one points to a temporary stop, but the seller refuses to guide travelers on rumor alone.'],
    objective: ['用现场风向核对铜线布片。', 'Check the copper-thread cloth against the current wind.'],
    choices: [['把布片边缘对准雨棚滴水线', 'Align the cloth edge with the awning drip line'], ['询问来客描述过哪一种铜线角度', 'Ask which copper-thread angle the visitor described'], ['暂不传递路线，只记录现场风向', 'Withhold the route and record only the present wind']],
    imagePrompt: `${POV}, adult spice seller holding an unmarked dark cloth stitched with five angled copper threads, awning drip line behind as a wind reference, ${GOUACHE}`,
  },

  {
    id: 'silverleaf-blue-moths', locationId: 'silverleaf-vineyard', category: 'environment',
    choiceLabel: ['查看停在葡萄藤背面的蓝翅蛾群', 'Inspect the blue-winged moths beneath the vines'],
    text: ['一排葡萄叶同时翻起银白背面，十几只蓝翅蛾停在叶脉上，却没有啃食。它们都朝果园方向收拢触须，像在等待同一束光。', 'A row of vine leaves turns its silver undersides at once. A dozen blue-winged moths rest along the veins without feeding, all folding their feelers toward the orchard as though waiting for one light.'],
    objective: ['判断蓝翅蛾为何停在葡萄叶背面。', 'Determine why the blue-winged moths are waiting beneath the leaves.'],
    choices: [['观察蛾群对月线灯光的反应', 'Watch how the moths react to the Moonline lamps'], ['检查叶脉是否沾有果园花粉', 'Check the veins for orchard pollen'], ['沿藤架寻找最先翻面的叶片', 'Find the first leaf that turned on the trellis']],
    imagePrompt: `${POV}, silver undersides of grape leaves close overhead with a cluster of blue-winged moths resting along the veins, distant orchard lights, ${GOUACHE}`,
  },
  {
    id: 'silverleaf-harvest-table', locationId: 'silverleaf-vineyard', category: 'daily-life',
    choiceLabel: ['帮采收桌分清三篮不同成熟度的葡萄', 'Help the harvest table sort three baskets by ripeness'],
    text: ['采收桌上并排放着三篮葡萄：一篮果梗仍青，一篮果皮带银粉，一篮在夜露里裂了口。负责记录的人不催你搬，只请你先说哪一篮必须马上处理。', 'Three grape baskets sit on the harvest table: one with green stems, one with silver bloom, and one split by night dew. The recorder does not ask you to carry them yet, only to say which needs attention first.'],
    objective: ['决定三篮葡萄的处理顺序。', 'Set the handling order for the three grape baskets.'],
    choices: [['先挑出夜露中裂口的葡萄', 'Separate the grapes split by night dew first'], ['检查银粉是否完整覆盖果皮', 'Check whether the silver bloom fully coats the skins'], ['问记录员青果梗要留给哪一批', 'Ask which batch should keep the green-stem fruit']],
    imagePrompt: `${POV}, three grape baskets on a weathered harvest table, green stems, silver bloom and dew-split skins clearly distinct, adult recorder opposite, ${GOUACHE}`,
  },
  {
    id: 'silverleaf-trellis-ties', locationId: 'silverleaf-vineyard', category: 'local-work',
    choiceLabel: ['检查雨后松开的藤架绑带', 'Inspect the trellis ties loosened by rain'],
    text: ['雨后第三排藤架向下沉了一寸，五条旧绑带先后松开。领班说修补可以计工，但必须先确认木桩没有裂，才会报出完整报酬。', 'After the rain, the third trellis row has sagged an inch and five old ties have loosened. The lead says repair can be paid work, but the posts must be checked for splits before a full wage is quoted.'],
    objective: ['确认第三排藤架是绑带松动还是木桩开裂。', 'Confirm whether the third trellis row has loose ties or split posts.'],
    choices: [['沿第三排逐根检查木桩裂纹', 'Check each post in the third row for splits'], ['问领班确认后按多少工时结算', 'Ask how many hours will be paid after inspection'], ['先用支杆托住最低的一段藤架', 'Brace the lowest trellis section with a support']],
    imagePrompt: `low wide view beneath a sagging vineyard trellis after rain, five loose cloth ties and intact-looking posts, workers held at distance, protagonist absent, ${GOUACHE}`,
  },
  {
    id: 'silverleaf-orchard-pollen-vial', locationId: 'silverleaf-vineyard', category: 'cross-region',
    choiceLabel: ['核对从云阶果园送来的花粉瓶', 'Check the pollen vial sent from Cloudstep Orchard'],
    text: ['葡萄丘收到一只封口完好的小玻璃瓶，瓶内金灰色花粉分成两层。送货绳结属于云阶果园，但瓶塞上多了一圈海盐，说明途中至少换过一次交通。', 'The vineyard receives a sealed glass vial whose gold-gray pollen has separated into two layers. Its delivery knot belongs to Cloudstep Orchard, but a ring of sea salt on the stopper shows that it changed transport at least once.'],
    objective: ['在不开瓶的情况下核对果园花粉瓶的运输路线。', 'Verify the orchard pollen vial’s route without opening it.'],
    choices: [['比较瓶塞海盐和月线窗沿盐迹', 'Compare the stopper salt with Moonline window residue'], ['检查果园绳结是否重新系过', 'Check whether the orchard knot was retied'], ['暂时隔离花粉瓶并询问送货人', 'Set the vial aside and question the courier']],
    imagePrompt: `${POV}, one sealed glass pollen vial held in a padded wooden cradle, two layers of gold-gray pollen and a sea-salt ring on the stopper, vineyard table, ${GOUACHE}`,
  },

  {
    id: 'mistpine-bell-vine', locationId: 'mistpine-forest', category: 'environment',
    choiceLabel: ['寻找没有风却响起的铃藤', 'Find the bell vine ringing without wind'],
    text: ['雾杉林深处传来三声轻响，附近枝叶却完全不动。声音来自一株缠在旧界石上的铃藤，三只空果壳依次碰撞，根边泥土有新鲜翻动。', 'Three light notes sound in Mistpine Forest while nearby leaves remain still. They come from a bell vine wound around an old boundary stone; three hollow pods strike in sequence, and the soil at its roots is freshly disturbed.'],
    objective: ['查明无风时铃藤为何响起。', 'Find why the bell vine rings without wind.'],
    choices: [['检查铃藤根边新翻的泥土', 'Inspect the freshly turned soil at the vine roots'], ['观察三只空果壳的碰撞顺序', 'Watch the order in which the three pods strike'], ['沿旧界石寻找其他受扰动痕迹', 'Search the old boundary stone for other disturbances']],
    imagePrompt: `${POV}, three hollow bell-vine pods hanging around a mossy boundary stone in still fog, freshly turned dark soil at the roots, ${GOUACHE}`,
  },
  {
    id: 'mistpine-charcoal-tea', locationId: 'mistpine-forest', category: 'daily-life',
    choiceLabel: ['加入护林棚旁的炭火茶圈', 'Join the charcoal tea circle by the ranger shelter'],
    text: ['护林棚旁，三名巡路人把湿手套围在小炭炉边烘干。茶壶只剩半壶，他们没有默认你要喝，而是先指给你一张空凳和一块能避开烟的地方。', 'Beside the ranger shelter, three route walkers dry wet gloves around a small charcoal brazier. Only half a pot of tea remains; they do not assume you want any, pointing first to an empty stool and a place clear of smoke.'],
    objective: ['决定是否在护林棚茶圈停留。', 'Decide whether to stay at the ranger-shelter tea circle.'],
    choices: [['先问这壶茶是否需要分摊', 'Ask whether the tea needs to be shared or paid for'], ['坐到避烟的空凳听巡路消息', 'Sit on the smoke-free stool and hear route news'], ['帮忙把湿手套翻到另一面', 'Help turn the wet gloves to the dry side']],
    imagePrompt: `${POV}, three adult route walkers around a small charcoal brazier outside a forest shelter, one empty stool and half-full plain teapot offered without hands entering frame, ${GOUACHE}`,
  },
  {
    id: 'mistpine-footbridge-marker', locationId: 'mistpine-forest', category: 'local-work',
    choiceLabel: ['检查溪桥旁歪斜的无字路标', 'Inspect the leaning blank route marker by the creek bridge'],
    text: ['溪桥旁的无字木标向下歪了半圈，底座被雨水淘空。护林员说可以付钱请人扶正，但先要判断桥桩是否也被水冲松。', 'The blank wooden route marker by the creek bridge has twisted half a turn, its base washed hollow. A ranger says righting it can be paid work, but the bridge piles must first be checked for water damage.'],
    objective: ['确认溪桥路标和桥桩的受损范围。', 'Confirm the damage to the creek marker and bridge piles.'],
    choices: [['从岸边检查最近的桥桩', 'Inspect the nearest bridge pile from the bank'], ['问护林员检查后的具体报酬', 'Ask the ranger for exact pay after inspection'], ['先用石块挡住路标底座水流', 'Divert water from the marker base with stones']],
    imagePrompt: `wide creekside view of a leaning blank wooden marker and a narrow footbridge in mist, exposed washed-out base visible, protagonist absent, ${GOUACHE}`,
  },
  {
    id: 'mistpine-wet-map-page', locationId: 'mistpine-forest', category: 'visitor',
    choiceLabel: ['查看陌生旅人晾在树枝上的湿地图页', 'Inspect the wet map page a traveler hung on a branch'],
    text: ['一名陌生旅人把一张没有字的地图页晾在低枝上。纸边压着风崖常用的铜线，中央却粘着葡萄丘的银叶；旅人只知道它从月线车门缝里吹进来。', 'A stranger hangs an unmarked map page from a low branch to dry. Windglass copper wire weighs one edge, while a Silverleaf vine leaf clings to the center; the traveler only knows it blew through a Moonline door gap.'],
    objective: ['根据地图页外部痕迹判断它经过的地方。', 'Use the map page’s external traces to infer where it traveled.'],
    choices: [['检查铜线的风崖固定方式', 'Inspect the Windglass fastening pattern in the wire'], ['比较银叶和林中藤叶的差别', 'Compare the silver vine leaf with forest foliage'], ['请旅人回忆地图页吹入时的站名', 'Ask the traveler to recall the stop where it blew in']],
    imagePrompt: `${POV}, adult traveler holding one wet unmarked map page against a low pine branch, copper wire and one silver vine leaf as visible clues, ${GOUACHE}`,
  },

  {
    id: 'tidal-glowing-pools', locationId: 'tidal-islands', category: 'environment',
    choiceLabel: ['查看退潮石池里逆流移动的微光', 'Inspect the lights moving against the tide in a rock pool'],
    text: ['退潮后的石池里，几粒青白微光逆着水纹移动，最后聚到一枚破损的渡船扣环旁。它们没有靠近你的倒影，只绕着金属缺口打转。', 'In a rock pool left by the ebb, several blue-white lights move against the ripples and gather around a broken ferry clasp. They avoid your reflection and circle only the gap in the metal.'],
    objective: ['查明石池微光为何围绕破损扣环。', 'Find why the rock-pool lights circle the broken clasp.'],
    choices: [['观察微光经过金属缺口时的变化', 'Watch how the lights change at the metal gap'], ['从池外检查扣环断面', 'Inspect the clasp fracture from outside the pool'], ['沿退潮水纹寻找另一枚扣环', 'Trace the ebb ripples for a matching clasp']],
    imagePrompt: `${POV}, shallow tidal rock pool with blue-white lights moving around one broken ferry clasp, wet stone and moon reflection, protagonist absent, ${GOUACHE}`,
  },
  {
    id: 'tidal-net-circle', locationId: 'tidal-islands', category: 'daily-life',
    choiceLabel: ['加入晒网架下的补网圈', 'Join the net-mending circle beneath the drying racks'],
    text: ['晒网架下，岛民正把一张破网分成粗绳、细线和浮木三段修。一个空针板推到你面前，但负责的人先说明这是邻里互助，不会自动算成有报酬的工作。', 'Beneath the drying racks, islanders divide a torn net into coarse rope, fine line, and floatwood sections. An empty needle board is pushed toward you, but the organizer first explains that this is neighborly help, not automatically paid work.'],
    objective: ['决定是否参与岛民的补网互助。', 'Decide whether to join the islanders’ net-mending help.'],
    choices: [['先学粗绳段的固定结', 'Learn the fastening knot for the coarse-rope section'], ['帮忙把浮木按磨损程度排开', 'Sort the floats by wear'], ['询问附近是否另有正式付费班次', 'Ask whether a separate paid shift is available nearby']],
    imagePrompt: `${POV}, adult islanders mending one large net beneath drying racks, an empty wooden needle board at the near edge, rope and floats separated, ${GOUACHE}`,
  },
  {
    id: 'tidal-instrument-case', locationId: 'tidal-islands', category: 'visitor',
    choiceLabel: ['查看搁浅在码头柱边的乐器箱', 'Inspect the instrument case stranded by a pier post'],
    text: ['潮水在码头柱边留下一只黑木乐器箱。箱体没有进水，铜扣上却缠着杯影夜市常用的陶红舞台线；岛上的乐师都说不是自己的。', 'The tide leaves a blackwood instrument case beside a pier post. It has taken no water, but its brass clasp is tangled with terracotta stage cord used at Cupshadow Market; every island musician says it is not theirs.'],
    objective: ['不打开乐器箱，确认它来自哪一支沿线演出队。', 'Identify the route performance troupe without opening the case.'],
    choices: [['请岛上乐师辨认陶红舞台线', 'Ask the island musicians to identify the terracotta stage cord'], ['检查箱底是否有月线货架压痕', 'Check the case base for Moonline rack marks'], ['把乐器箱移到干燥失物架', 'Move the case to the dry lost-property rack']],
    imagePrompt: `${POV}, one closed blackwood instrument case against a wet pier post, terracotta stage cord tangled around its brass clasp, adult island musician nearby, ${GOUACHE}`,
  },
  {
    id: 'tidal-lock-token', locationId: 'tidal-islands', category: 'cross-region',
    choiceLabel: ['核对渡船带来的木水闸模型', 'Check the wooden lock-gate model brought by the ferry'],
    text: ['渡船带来一只手掌长的木水闸模型，三片闸板中只有中间一片会卡住。模型底部粘着芦水渡村的青苔，显然是给岛上船工看的故障样本。', 'A ferry brings a palm-long wooden lock-gate model whose middle panel alone sticks. Reedwater moss clings beneath it, marking it as a fault sample for the island boatworkers.'],
    objective: ['用木水闸模型判断渡村闸门的故障。', 'Use the wooden model to diagnose the Reedwater lock fault.'],
    choices: [['推动中间闸板寻找卡点', 'Move the middle gate panel to find the catch'], ['比较三片闸板边缘的磨损', 'Compare wear along the three panel edges'], ['请渡船员说明模型由谁交来', 'Ask who gave the model to the ferry crew']],
    imagePrompt: `${POV}, adult ferry worker presenting one palm-sized wooden lock-gate model on a pier crate, middle panel visibly stuck and reed moss beneath, ${GOUACHE}`,
  },

  {
    id: 'far-lantern-warm-step', locationId: 'far-lantern-institute', category: 'environment',
    choiceLabel: ['查看雨后仍然温热的西侧石阶', 'Inspect the west stone step that remains warm after rain'],
    text: ['研修院西侧石阶被雨淋透，只有第六级仍然温热，水珠在表面慢慢退开。石边嵌着与旧石坑相同的铜色细纹，却没有任何火源。', 'Rain soaks the institute’s west steps, yet the sixth remains warm and beads of water slowly retreat from it. Copper-colored veins match stone from the old quarry, though no heat source is nearby.'],
    objective: ['判断西侧第六级石阶为何保持温热。', 'Determine why the sixth west step remains warm.'],
    choices: [['比较温热石阶和相邻石阶的纹路', 'Compare the warm step’s veins with its neighbors'], ['询问修缮记录里石材来自哪里', 'Ask where the repair records say the stone came from'], ['等水珠退完再检查温热范围', 'Wait for the droplets to recede and check the warm area']],
    imagePrompt: `${POV}, rain-wet institute stone stairs, one step visibly drying around fine copper-colored mineral veins while adjacent steps remain wet, ${GOUACHE}`,
  },
  {
    id: 'far-lantern-lecture-objects', locationId: 'far-lantern-institute', category: 'daily-life',
    choiceLabel: ['帮公开讲堂摆放三件无字演示物', 'Help arrange three unmarked demonstration objects in the public hall'],
    text: ['公开讲堂要做一场沿岸生活演示，桌上只有盐镜、旧藤绑带和木水闸模型，没有标签。主持人请你按“天气、种植、交通”的顺序摆放，同时保留它们之间的联系。', 'The public hall is preparing a coastal-life demonstration with an unmarked salt mirror, an old vine tie, and a wooden lock model. The host asks you to arrange weather, cultivation, and transport while preserving their connections.'],
    objective: ['为公开讲堂安排三件沿岸演示物。', 'Arrange the three coastal demonstration objects for the public hall.'],
    choices: [['把盐镜放在最先看见的位置', 'Place the salt mirror where it is seen first'], ['用旧藤绑带连接盐镜和水闸模型', 'Use the old vine tie to connect the mirror and lock model'], ['先问主持人观众需要理解哪件事', 'Ask what the audience must understand first']],
    imagePrompt: `${POV}, adult public-hall host across a table with one salt mirror, one old vine tie and one wooden lock model, all unmarked, ${GOUACHE}`,
  },
  {
    id: 'far-lantern-archive-shelf', locationId: 'far-lantern-institute', category: 'local-work',
    choiceLabel: ['检查档案室向一侧倾斜的木架', 'Inspect the archive shelf leaning to one side'],
    text: ['档案室一排空木架向左倾斜，底脚下压着碎石。管理员说明搬架和找平可以计工，但要先确认墙面没有受潮，之后才会报出工时和钱数。', 'A row of empty archive shelves leans left over crushed stone. The keeper says moving and leveling them can be paid work, but the wall must first be checked for damp before hours and wages are quoted.'],
    objective: ['确认档案木架倾斜的原因。', 'Confirm why the archive shelving is leaning.'],
    choices: [['检查木架背后的墙面水痕', 'Check the wall behind the shelf for damp'], ['问管理员确认后如何计算报酬', 'Ask how pay will be calculated after inspection'], ['先清空倾斜木架附近的通道', 'Clear the passage beside the leaning shelf']],
    imagePrompt: `wide interior view of empty wooden archive shelves leaning over crushed stone beside a pale damp wall, adult keeper at safe distance, no protagonist, ${GOUACHE}`,
  },
  {
    id: 'far-lantern-salt-mirror', locationId: 'far-lantern-institute', category: 'cross-region',
    choiceLabel: ['接收从风崖送来的裂纹盐镜', 'Receive the cracked salt mirror sent from Windglass'],
    text: ['一只包着软布的盐镜送到研修院，裂纹从中心向三个方向延伸。送件人没有要求你签收，只说明风崖观测员想知道裂纹是否与旧海岸图的缺口方向一致。', 'A salt mirror wrapped in soft cloth reaches the institute, cracked from the center in three directions. The courier does not ask you to accept ownership, only says the Windglass observer wants to know whether the fractures match the missing section of an old coastal map.'],
    objective: ['比较裂纹盐镜和旧海岸图缺口的方向。', 'Compare the salt-mirror fractures with the missing coast-map section.'],
    choices: [['把盐镜放在空白地图旁对齐裂纹', 'Align the cracked mirror beside the blank map section'], ['询问送件人风崖何时发现裂纹', 'Ask when Windglass first found the crack'], ['不移动盐镜，先请档案员取旧图', 'Leave the mirror still and ask for the old map']],
    imagePrompt: `${POV}, adult courier uncovering one cracked salt mirror beside an unmarked coastal map with a missing section, three fracture directions visible, ${GOUACHE}`,
  },

  {
    id: 'windglass-seabird-circle', locationId: 'windglass-cliffs', category: 'environment',
    choiceLabel: ['观察始终绕开信号塔的海鸟群', 'Watch the seabirds circling around the signal tower'],
    text: ['海鸟沿崖顶盘旋，却在接近信号塔时整齐向外偏开。塔灯尚未点亮，盐镜表面却出现一条窄暗带，正好与鸟群避开的方向重合。', 'Seabirds circle the cliff top but veer outward together near the signal tower. The lamp is not lit, yet a narrow dark band crosses the salt mirror in the same direction the flock avoids.'],
    objective: ['判断海鸟为何避开信号塔一侧。', 'Determine why the seabirds avoid one side of the signal tower.'],
    choices: [['对照鸟群转向和盐镜暗带', 'Compare the flock’s turn with the mirror’s dark band'], ['检查塔外是否有松动金属件', 'Check outside the tower for loose metal'], ['等下一阵风看鸟群是否改变路线', 'Wait for the next gust and watch the route change']],
    imagePrompt: `${POV}, cliff signal tower edge and a salt mirror with one dark band, seabirds curving away in the same direction over the sea, ${GOUACHE}`,
  },
  {
    id: 'windglass-soup-flask', locationId: 'windglass-cliffs', category: 'daily-life',
    choiceLabel: ['帮值守人分配只剩两杯的热汤', 'Help the watch crew share the last two cups of hot soup'],
    text: ['信号塔值守间只剩两杯热汤，今晚却有三个人换班。值守人没有把汤算作工资，也没有默认让给谁，而是把杯子和下一次补给时间都摆明。', 'Only two cups of hot soup remain in the signal room for three people changing watch. The crew does not count it as wages or assume who gives it up, laying out the cups and the next supply time plainly.'],
    objective: ['决定信号塔最后两杯热汤如何分配。', 'Decide how the signal crew should share the last two cups of soup.'],
    choices: [['先问谁刚从崖外巡线回来', 'Ask who just returned from the outer cliff route'], ['把两杯汤分成三个小杯', 'Divide the two cups into three smaller servings'], ['查看下一次补给还有多久', 'Check how long until the next supply run']],
    imagePrompt: `${POV}, two steaming plain cups on a signal-room table with three adult watchkeepers opposite, storm glass and cliff window behind, ${GOUACHE}`,
  },
  {
    id: 'windglass-windsock-cable', locationId: 'windglass-cliffs', category: 'local-work',
    choiceLabel: ['检查信号塔风筒的松动拉索', 'Inspect the loose windsock cable at the signal tower'],
    text: ['风筒拉索在铜环里磨出一道亮痕，再刮一次大风就可能脱开。值守领班可以付钱请人更换，但先要从安全平台判断铜环是否也裂了。', 'The windsock cable has worn a bright groove in its copper ring and may break free in the next hard gust. The watch lead can pay for replacement, but the ring must first be inspected from the safe platform.'],
    objective: ['确认风筒拉索和铜环的磨损程度。', 'Confirm wear on the windsock cable and copper ring.'],
    choices: [['从安全平台用镜片检查铜环', 'Use a mirror from the safe platform to inspect the ring'], ['问领班检查后的具体工时和报酬', 'Ask for exact hours and pay after inspection'], ['先放下备用风筒避免继续受力', 'Lower the spare windsock to reduce strain']],
    imagePrompt: `wide upward view of a windsock cable worn bright inside one copper ring on a cliff signal tower, safe platform and sea below, no protagonist, ${GOUACHE}`,
  },
  {
    id: 'windglass-map-alignment', locationId: 'windglass-cliffs', category: 'cross-region',
    choiceLabel: ['把旧海岸图和崖下真实岬角对齐', 'Align the old coast map with the real headlands below'],
    text: ['观测桌上压着一张没有字的旧海岸图。图纸在第三个岬角后突然留白，崖下真实海岸却多出一条窄湾；远灯研修院的铜钉孔正位于留白边缘。', 'An unmarked old coast map lies on the observation table. It goes blank after the third headland, while the real coast below contains a narrow inlet; a Far Lantern pinhole sits at the edge of the blank.'],
    objective: ['核对旧海岸图留白和真实窄湾。', 'Check the map blank against the real narrow inlet.'],
    choices: [['用观测桌边缘对齐第三个岬角', 'Align the third headland with the table edge'], ['检查远灯铜钉孔原本固定的位置', 'Inspect where the Far Lantern pinhole was fixed'], ['记录窄湾潮线，不替旧图补画', 'Record the inlet tide line without redrawing the map']],
    imagePrompt: `${POV}, one unmarked old coastal map aligned against real headlands below a cliff, blank section beside a narrow inlet, copper pinhole visible, ${GOUACHE}`,
  },

  {
    id: 'reedwater-floating-reeds', locationId: 'reedwater-crossing', category: 'environment',
    choiceLabel: ['查看逆着闸门水流聚拢的芦苇', 'Inspect reeds gathering against the lock current'],
    text: ['水闸放水时，几束断芦苇没有顺流而下，反而贴着东侧闸板聚成半圆。水面下偶尔露出一截旧绳，像有什么东西挂在闸脚。', 'As the lock releases water, broken reeds do not drift downstream but gather in a half-circle against the east gate. A length of old rope shows beneath the surface, as though something is caught at the foot.'],
    objective: ['判断东侧闸脚下挂住了什么。', 'Determine what is caught beneath the east lock gate.'],
    choices: [['从岸上观察旧绳受力方向', 'Watch the old rope’s tension from the bank'], ['请闸工减小一次放水量', 'Ask the lock worker to reduce one release'], ['沿芦苇半圆寻找绳索另一端', 'Trace the reed arc for the rope’s other end']],
    imagePrompt: `${POV}, broken reeds forming a half-circle against a wooden lock gate, one old rope visible beneath moving water, adult lock worker nearby, ${GOUACHE}`,
  },
  {
    id: 'reedwater-umbrella-queue', locationId: 'reedwater-crossing', category: 'daily-life',
    choiceLabel: ['帮候船人重新安排共用雨伞', 'Help the ferry queue reorganize shared umbrellas'],
    text: ['短雨突然落下，候船棚里有四把共用伞，却有六个人要去两个不同码头。排队的人把目的地和返还时间说清，没有人要求你替谁先走。', 'A brief rain begins. The ferry shelter has four shared umbrellas for six people heading to two piers. Everyone states destination and return time, and nobody asks you to choose favorites.'],
    objective: ['让四把共用伞覆盖两个码头的候船人。', 'Arrange four shared umbrellas for passengers at two piers.'],
    choices: [['先按东码头和西码头分组', 'Group passengers by east and west pier'], ['找出最早能返还的两把伞', 'Find the two umbrellas that can return first'], ['请留在棚里的人共享等待时间', 'Ask those staying under shelter to share the wait']],
    imagePrompt: `${POV}, six adult ferry passengers beneath a reed shelter with four plain shared umbrellas laid between two pier directions, rain beyond, ${GOUACHE}`,
  },
  {
    id: 'reedwater-rope-channel', locationId: 'reedwater-crossing', category: 'local-work',
    choiceLabel: ['检查渡船副绳槽里的断芦苇', 'Inspect broken reeds in the ferry’s secondary rope channel'],
    text: ['渡船副绳槽被断芦苇塞住，主绳仍能工作，但下一次涨潮前必须清理。修理工说可以计工，先要确认槽轮没有缺齿，再报出准确工时和报酬。', 'Broken reeds clog the ferry’s secondary rope channel. The main line still works, but the channel must be cleared before high tide. The mechanic says it can be paid work, after the wheel teeth are checked and exact hours and wages are quoted.'],
    objective: ['确认副绳槽堵塞是否伤到槽轮。', 'Confirm whether the secondary-channel blockage damaged the wheel.'],
    choices: [['用木杆从岸上拨开表层芦苇', 'Use a wooden pole to move surface reeds from shore'], ['检查露出的槽轮齿是否完整', 'Check the exposed wheel teeth for damage'], ['问修理工确认后的准确报酬', 'Ask the mechanic for exact pay after inspection']],
    imagePrompt: `wide practical view of a small ferry rope channel clogged with broken reeds, exposed wooden wheel teeth beside the bank, adult mechanic, no protagonist, ${GOUACHE}`,
  },
  {
    id: 'reedwater-island-parcel', locationId: 'reedwater-crossing', category: 'cross-region',
    choiceLabel: ['核对要转送潮汐群岛的防水包裹', 'Check the waterproof parcel bound for the Tidal Islands'],
    text: ['渡船台收到一只封好的防水包裹，外层绳结属于潮汐群岛，底部却沾着旧石坑的浅灰石粉。包裹没有破损，收件人栏只有一枚无字木片。', 'The ferry platform receives a sealed waterproof parcel tied with a Tidal Islands knot but dusted underneath with pale Old Quarry stone. It is undamaged, and its recipient marker is a blank wooden token.'],
    objective: ['在不拆包的情况下确认群岛包裹的转送依据。', 'Confirm the island parcel’s routing without opening it.'],
    choices: [['比较无字木片和岛上渡船标记', 'Compare the blank token with island ferry markers'], ['询问包裹从哪个月线站转来', 'Ask which Moonline stop transferred the parcel'], ['暂缓上船并记录浅灰石粉', 'Hold the parcel ashore and record the pale stone dust']],
    imagePrompt: `${POV}, adult ferry clerk presenting one sealed waterproof parcel with island rope knot, blank wooden token and pale stone dust beneath, ${GOUACHE}`,
  },

  {
    id: 'whitecap-steam-vents', locationId: 'whitecap-baths', category: 'environment',
    choiceLabel: ['查看蒸汽露台上忽冷忽热的三处气孔', 'Inspect three steam vents changing temperature on the terrace'],
    text: ['蒸汽露台的三处气孔依次变冷，又从中间一处重新升温。石面没有裂，最靠外的气孔边却积了一圈细砂，像水路把杂质推到了末端。', 'Three vents on the steam terrace cool in sequence, then warm again from the middle. The stone is uncracked, but fine grit rings the outer vent as though the water line pushed debris to its end.'],
    objective: ['判断蒸汽露台三处气孔的水路变化。', 'Determine what changed in the three terrace steam vents.'],
    choices: [['按顺序比较三处气孔温度', 'Compare the three vent temperatures in order'], ['检查最外侧气孔的细砂', 'Inspect the grit around the outer vent'], ['请浴场管事查看进水阀', 'Ask the bath steward to check the intake valve']],
    imagePrompt: `${POV}, three stone steam vents on a terrace cooling in sequence, fine grit around the outer vent and pale steam returning at center, ${GOUACHE}`,
  },
  {
    id: 'whitecap-lost-gloves', locationId: 'whitecap-baths', category: 'daily-life',
    choiceLabel: ['帮失物架配对五只不同的手套', 'Help match five odd gloves on the lost-property shelf'],
    text: ['浴场失物架上留下五只单手套：一只沾葡萄粉，一只带风崖铜线，两只袖口相同，最后一只缝着石灰色补丁。管事只让你按可见痕迹配对，不猜主人的身份。', 'Five single gloves remain on the bathhouse lost-property shelf: one with grape bloom, one with Windglass wire, two with matching cuffs, and one with a limestone-gray patch. The steward asks you to pair visible evidence without guessing owners.'],
    objective: ['按可见痕迹整理浴场失物手套。', 'Sort the bathhouse gloves using visible evidence.'],
    choices: [['先把袖口相同的两只放在一起', 'Pair the two gloves with matching cuffs'], ['分别记录葡萄粉和铜线来源', 'Record the grape bloom and copper wire separately'], ['把石灰补丁手套留作单独待认领', 'Leave the limestone-patched glove separate']],
    imagePrompt: `${POV}, five mismatched work gloves on a pale lost-property shelf, visible grape bloom, copper wire, matching cuffs and limestone patch, adult steward opposite, ${GOUACHE}`,
  },
  {
    id: 'whitecap-laundry-pulley', locationId: 'whitecap-baths', category: 'local-work',
    choiceLabel: ['检查洗衣院卡住的晾绳滑轮', 'Inspect the jammed laundry-line pulley'],
    text: ['洗衣院的晾绳滑轮卡在半空，湿布没有掉落，但继续拉可能扯断主绳。值班人说维修可以计工，要先从地面找出卡住的是木屑还是皂垢，再说明报酬。', 'The laundry-line pulley is stuck halfway up. The wet cloths remain secure, but another pull may break the main line. The attendant says repair can be paid work after a ground inspection determines whether wood splinters or soap residue caused the jam.'],
    objective: ['确认晾绳滑轮被木屑还是皂垢卡住。', 'Confirm whether splinters or soap residue jammed the pulley.'],
    choices: [['用长柄镜从地面查看滑轮槽', 'Use a long-handled mirror to inspect the groove'], ['先松开备用绳减轻主绳受力', 'Release the spare line to reduce strain'], ['问值班人检查后的准确报酬', 'Ask the attendant for exact pay after inspection']],
    imagePrompt: `wide upward laundry-court view of a jammed wooden pulley holding wet cloth lines above steam, long inspection mirror below, no protagonist, ${GOUACHE}`,
  },
  {
    id: 'whitecap-show-tokens', locationId: 'whitecap-baths', category: 'cross-region',
    choiceLabel: ['核对公共厨房收到的无字餐牌', 'Check the blank meal tokens delivered to the public kitchen'],
    text: ['公共厨房收到六枚没有字的陶制餐牌，三枚沾杯影舞台的陶红线，另外三枚带潮汐群岛的贝壳粉。厨房不会凭餐牌自动出餐，需要先确认是哪一场沿线演出留下的。', 'The public kitchen receives six blank ceramic meal tokens. Three carry Cupshadow terracotta stage thread, and three bear shell dust from the Tidal Islands. The kitchen will not serve meals automatically until the route performance is identified.'],
    objective: ['确认六枚无字餐牌属于哪场沿线演出。', 'Identify which route performance owns the six blank meal tokens.'],
    choices: [['把陶红线餐牌和贝壳粉餐牌分开', 'Separate the terracotta-thread and shell-dust tokens'], ['询问厨房最近接待过哪支演出队', 'Ask which troupe the kitchen hosted most recently'], ['把餐牌留在柜台等待演出人员认领', 'Leave the tokens at the counter for the troupe']],
    imagePrompt: `${POV}, six blank ceramic meal tokens on a public-kitchen counter, three with terracotta thread and three with shell dust, adult kitchen steward beyond, ${GOUACHE}`,
  },

  {
    id: 'old-quarry-warm-seam', locationId: 'old-quarry-gardens', category: 'environment',
    choiceLabel: ['观察月光下升温的窄石脉', 'Observe the narrow stone seam warming in moonlight'],
    text: ['梯田边一条指宽的矿脉在月光下慢慢升温，周围青苔却没有干枯。热度只沿铜色颗粒前进，到一处旧凿痕便突然停止。', 'A finger-wide mineral seam beside the terraces slowly warms under moonlight without drying the surrounding moss. Heat follows copper-colored grains and stops abruptly at an old chisel mark.'],
    objective: ['查明月暖石脉为何在旧凿痕处停止升温。', 'Find why the moon-warmed seam stops at the old chisel mark.'],
    choices: [['观察铜色颗粒在凿痕两侧的差别', 'Compare copper grains on both sides of the mark'], ['不取样，只测凿痕附近的温度', 'Take no sample and compare temperature near the mark'], ['沿石脉寻找另一处旧凿痕', 'Follow the seam for another old chisel mark']],
    imagePrompt: `${POV}, narrow copper-grained mineral seam warming under moonlight through mossy quarry stone, glow stopping at one old chisel mark, ${GOUACHE}`,
  },
  {
    id: 'old-quarry-seed-table', locationId: 'old-quarry-gardens', category: 'daily-life',
    choiceLabel: ['帮梯田种子桌分清耐阴和耐风种子', 'Help the terrace seed table separate shade and wind varieties'],
    text: ['梯田种子桌上摆着四只无字浅盘，两盘种子带细绒，两盘外壳光滑。园丁说细绒能挂住风，光壳更适合阴湿石缝，但其中一盘混进了银叶葡萄籽。', 'Four unmarked shallow trays sit on the terrace seed table: two with downy seeds and two with smooth shells. A gardener explains that down catches wind and smooth shells suit damp shade, but one tray contains stray Silverleaf grape seeds.'],
    objective: ['把梯田种子按耐风、耐阴和葡萄籽分开。', 'Sort the terrace seeds into wind, shade, and grape groups.'],
    choices: [['先挑出形状不同的葡萄籽', 'Separate the differently shaped grape seeds first'], ['比较两盘细绒种子的绒毛方向', 'Compare the down direction in the two fuzzy trays'], ['请园丁指出阴湿石缝的实物样本', 'Ask the gardener to show a damp-shade example']],
    imagePrompt: `${POV}, four unmarked shallow seed trays on a stone terrace table, downy seeds, smooth seeds and a few distinct grape pips, adult gardener opposite, ${GOUACHE}`,
  },
  {
    id: 'old-quarry-rain-channel', locationId: 'old-quarry-gardens', category: 'local-work',
    choiceLabel: ['检查蓄雨渠里松动的石片', 'Inspect loose stones in the rain channel'],
    text: ['第二层蓄雨渠里有三块石片轻轻晃动，水仍能通过，却开始冲走下面的园土。石工说重新铺石可以计工，先要确认石片背后有没有空洞，再报准确报酬。', 'Three stones wobble in the second-level rain channel. Water still passes, but it is washing away garden soil below. The stoneworker says relaying can be paid work after the cavity behind them is checked and exact pay is quoted.'],
    objective: ['确认三块松动石片后是否有空洞。', 'Confirm whether a cavity lies behind the three loose channel stones.'],
    choices: [['从水渠外侧听三块石片的回声', 'Listen to the three stones from outside the channel'], ['先把水流引向旁边的备用槽', 'Divert water into the spare channel'], ['问石工确认后的工时和报酬', 'Ask the stoneworker for hours and pay after inspection']],
    imagePrompt: `wide terraced quarry view of three loose flat stones in a rain channel with soil washing below, spare channel beside it, no protagonist, ${GOUACHE}`,
  },
  {
    id: 'old-quarry-institute-stones', locationId: 'old-quarry-gardens', category: 'cross-region',
    choiceLabel: ['核对准备送往远灯的三块旧石件', 'Check three old stone pieces bound for Far Lantern'],
    text: ['装运台上有三块旧石件：一块有排水槽，一块留着门轴孔，一块表面有月暖石纹。远灯研修院只要前两块修缮用石，第三块必须留在花园。', 'Three old stone pieces wait on the loading table: one has a drain groove, one a hinge socket, and one moon-warmed veining. Far Lantern requested only the first two for repairs; the third must remain in the gardens.'],
    objective: ['确认送往远灯的两块修缮石件。', 'Confirm the two repair stones bound for Far Lantern.'],
    choices: [['把排水槽石件移到远灯托架旁', 'Move the drain-groove stone beside the Far Lantern rack'], ['核对门轴孔石件的尺寸', 'Check the dimensions of the hinge-socket stone'], ['明确标出月暖石纹石件不得装运', 'Mark the moon-veined stone as not for transport']],
    imagePrompt: `${POV}, three distinct old stone pieces on a quarry loading table, drain groove, hinge socket and copper moon-veins clearly visible, adult stoneworker opposite, ${GOUACHE}`,
  },

  {
    id: 'cloudstep-moth-lamps', locationId: 'cloudstep-orchard', category: 'environment',
    choiceLabel: ['查看把蛾群引向空坡的授粉灯', 'Inspect pollination lamps drawing moths toward an empty slope'],
    text: ['果园授粉灯亮起后，蛾群没有飞向开花树排，反而聚到一段没有果树的空坡。空坡石缝里反射着一枚蓝白亮点，节奏与灯光完全相同。', 'When the orchard’s pollination lamps come on, the moths ignore the flowering rows and gather over an empty slope. A blue-white point in a stone crack mirrors the lamp rhythm exactly.'],
    objective: ['找出空坡亮点为何模仿授粉灯。', 'Find why the light on the empty slope mimics the pollination lamps.'],
    choices: [['遮住最近一盏授粉灯观察亮点', 'Shade the nearest pollination lamp and watch the point'], ['从坡下检查石缝里的反光物', 'Inspect the reflective object from below the slope'], ['暂时调暗空坡方向的两盏灯', 'Dim the two lamps facing the empty slope']],
    imagePrompt: `${POV}, orchard pollination lamps across flowering rows while moths gather over an empty slope around one blue-white reflection in stone, ${GOUACHE}`,
  },
  {
    id: 'cloudstep-bruised-fruit', locationId: 'cloudstep-orchard', category: 'daily-life',
    choiceLabel: ['帮包装棚处理一篮碰伤的果子', 'Help the packing shed handle a basket of bruised fruit'],
    text: ['包装棚发现一篮运输中碰伤的果子，不能再装箱，却还适合当天煮成果酱。负责的人把公共厨房、堆肥桶和试吃盘都摆出来，先说明没有任何一种处理会自动算成你的消费。', 'The packing shed finds a basket of fruit bruised in transit. It cannot be boxed but can still become same-day preserve. The keeper sets out a public-kitchen crate, compost bin, and tasting plate, explaining that none automatically counts as your purchase.'],
    objective: ['决定一篮碰伤果子的处理方式。', 'Decide how to handle the basket of bruised fruit.'],
    choices: [['挑出仍适合送公共厨房的果子', 'Select fruit still suitable for the public kitchen'], ['把完全破皮的果子送进堆肥桶', 'Put fully split fruit into the compost bin'], ['先问试吃盘是否免费提供', 'Ask whether the tasting plate is free']],
    imagePrompt: `${POV}, one basket of bruised orchard fruit on a packing table between a public-kitchen crate, compost bin and small tasting plate, adult keeper opposite, ${GOUACHE}`,
  },
  {
    id: 'cloudstep-crate-brace', locationId: 'cloudstep-orchard', category: 'local-work',
    choiceLabel: ['检查包装棚松动的果箱支架', 'Inspect the loose fruit-crate brace in the packing shed'],
    text: ['包装棚最下层果箱支架向外移了半寸，箱子尚未倾倒。棚主说加固可以计工，但先要卸下上层两只空箱，确认支架是钉子松动还是木条开裂。', 'The lowest fruit-crate brace has shifted half an inch outward, though no crates have fallen. The shed keeper says reinforcement can be paid work after two empty upper crates are removed and the loose nails or split slat identified.'],
    objective: ['确认果箱支架是钉子松动还是木条开裂。', 'Confirm whether loose nails or a split slat damaged the crate brace.'],
    choices: [['请棚主先卸下两只空箱', 'Ask the keeper to remove the two empty crates'], ['从侧面检查支架木条裂纹', 'Inspect the brace slat from the side'], ['问确认故障后的准确报酬', 'Ask for exact pay after the fault is confirmed']],
    imagePrompt: `wide packing-shed view of a lowest fruit-crate brace shifted outward beneath two empty crates, nails and wood slat visible, no protagonist, ${GOUACHE}`,
  },
  {
    id: 'cloudstep-rain-parcel', locationId: 'cloudstep-orchard', category: 'cross-region',
    choiceLabel: ['核对地址被雨洗掉的邮路包裹', 'Check the route parcel whose address washed away'],
    text: ['一只邮路包裹的地址被雨完全洗掉，封绳却保留三种痕迹：葡萄丘的银粉、浴镇的皂香和灯湾码头的蓝麻纤维。邮递员没有拆包，只把三个可能中转点列在桌边。', 'Rain has erased a route parcel’s address, but its cord retains three traces: Silverleaf bloom, Whitecap soap, and blue flax from Lantern Quay. The courier leaves it sealed and lays out the three possible transfer points.'],
    objective: ['根据封绳痕迹重建无地址包裹的邮路。', 'Reconstruct the addressless parcel’s route from its binding.'],
    choices: [['先判断蓝麻纤维是否是最早的痕迹', 'Determine whether blue flax is the earliest trace'], ['比较皂香在绳结内外的强弱', 'Compare soap scent inside and outside the knot'], ['核对银粉是否来自果箱还是葡萄藤', 'Check whether the silver bloom came from fruit crates or vines']],
    imagePrompt: `${POV}, adult courier presenting one sealed rain-wet parcel with erased surface, binding carrying blue flax fibers, pale soap residue and silver vine bloom, ${GOUACHE}`,
  },
]

export function wanderlightPresetEvents(locale: Locale): PresetEventDefinition[] {
  const index = locale === 'zh' ? 0 : 1
  return events.map((event) => ({
    id: event.id,
    locationId: event.locationId,
    category: event.category,
    choiceLabel: event.choiceLabel[index],
    text: event.text[index],
    objective: event.objective[index],
    choices: event.choices.map((choice) => choice[index]) as [string, ...string[]],
    imagePrompt: event.imagePrompt,
    imageSubject: 'environment',
  }))
}
